// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MonkeyShelterDbContext))]
    [Migration("20250430180413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Domain.DatabaseModels.AdmissionDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MonkeyAdmittanceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MonkeyCheckupTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonkeyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonkeyId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("Domain.DatabaseModels.DepartureDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonkeyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonkeyId");

                    b.ToTable("Departures");
                });

            modelBuilder.Entity("Domain.DatabaseModels.MonkeyDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShelterDbModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShelterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Species")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ShelterDbModelId");

                    b.ToTable("Monkeys");
                });

            modelBuilder.Entity("Domain.DatabaseModels.ShelterDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShelterManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShelterManagerId")
                        .IsUnique();

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("Domain.DatabaseModels.ShelterManagerDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShelterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShelterManagers");
                });

            modelBuilder.Entity("Domain.DatabaseModels.AdmissionDbModel", b =>
                {
                    b.HasOne("Domain.DatabaseModels.MonkeyDbModel", "Monkey")
                        .WithMany()
                        .HasForeignKey("MonkeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monkey");
                });

            modelBuilder.Entity("Domain.DatabaseModels.DepartureDbModel", b =>
                {
                    b.HasOne("Domain.DatabaseModels.MonkeyDbModel", "Monkey")
                        .WithMany()
                        .HasForeignKey("MonkeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monkey");
                });

            modelBuilder.Entity("Domain.DatabaseModels.MonkeyDbModel", b =>
                {
                    b.HasOne("Domain.DatabaseModels.ShelterDbModel", null)
                        .WithMany("Monkeys")
                        .HasForeignKey("ShelterDbModelId");
                });

            modelBuilder.Entity("Domain.DatabaseModels.ShelterDbModel", b =>
                {
                    b.HasOne("Domain.DatabaseModels.ShelterManagerDbModel", "ShelterManager")
                        .WithOne("Shelter")
                        .HasForeignKey("Domain.DatabaseModels.ShelterDbModel", "ShelterManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShelterManager");
                });

            modelBuilder.Entity("Domain.DatabaseModels.ShelterDbModel", b =>
                {
                    b.Navigation("Monkeys");
                });

            modelBuilder.Entity("Domain.DatabaseModels.ShelterManagerDbModel", b =>
                {
                    b.Navigation("Shelter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
